services:
  newsletter-local-db:
    image: postgres:15
    container_name: demo-local-db
    ports:
      - 6432:5432
    volumes:
      - ./local/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: demo_test
      POSTGRES_PASSWORD: demo_test_123
      POSTGRES_DB: demo_local